inputs_def:
  - handle: api_key
    description: "Financial Report Analysis API Key"
    json_schema:
      contentMediaType: oomol/secret
      type: string
    value: ${{OO_SECRET:FinancialAPI,Financial Report API,API_KEY}}

  - handle: ticker
    description: "Company stock ticker symbol (required for analysis)"
    json_schema:
      type: string
    value: ""
    nullable: false

  - handle: years
    description: "Number of years for analysis"
    json_schema:
      type: integer
    value: 1
    nullable: false

  - handle: question_group
    description: "Question group type (brief, detailed, etc.)"
    json_schema:
      type: string
    value: "brief"
    nullable: false

  - handle: question_ids
    description: "Array of specific question IDs"
    json_schema:
      type: array
      items:
        type: string
    value:
      []
    nullable: false

  - handle: batch
    description: "Whether to process in batch mode"
    json_schema:
      type: boolean
    value: false
    nullable: false

  - handle: use_cache
    description: "Whether to use cached results"
    json_schema:
      type: boolean
    value: true
    nullable: false

outputs_def:
  - handle: summary_result
    description: "Generated financial analysis summary"
    json_schema:
      type: object

  - handle: status
    description: "API call status"
    json_schema:
      type: string

  - handle: message
    description: "Status message or error details"
    json_schema:
      type: string

executor:
  name: python
  options:
    entry: __init__.py
    spawn: false

title: "Generate Report Summary"
icon: ":carbon:document-tasks:"
description: "Generate customized financial analysis summaries based on company
  data, time periods, and specific questions. Creates detailed analytical
  reports."
private: true
